[bastion]
BASTION ansible_host=192.168.0.99 host_name=BASTION net_iface=eth1

[all:vars]
INFLUXDBSRV=192.168.0.99
INFLUXDBPORT=2006
COLLECTD_DB_NAME=collectd_db
grafana_server=146.255.103.211
grafana_port=3000
grafana_admin=4dm1n
grafana_admin_passwd=4dm1nGrafana

[NODES:children]
WEBSRV
APPSRV
DBSRV

[WEBSRV]
PROWEB01 ansible_host=192.168.0.30 host_name=PROWEB01 net_iface=eth0
PROWEB02 ansible_host=192.168.0.35 host_name=PROWEB02 net_iface=eth0

[APPSRV]
PROAPP01 ansible_host=192.168.0.40 host_name=PROAPP01 net_iface=eth0
PROAPP02 ansible_host=192.168.0.45 host_name=PROAPP02 net_iface=eth0

[DBSRV]
PROMSQL01 ansible_host=192.168.0.50 host_name=PROMSQL01 net_iface=eth0
